/**
 * @constant
 * @desc every action type
 * @version 1.0
 * @since 1.0
 * @public
 */
export default {
    RECORD: 'RECORD::RECORD',
    RECORD_PENDING: 'RECORD::RECORD_PENDING',
    RECORD_FULFILLED: 'RECORD::RECORD_FULFILLED',
    RECORD_REJECTED: 'RECORD::RECORD_REJECTED',

    ADD_TO: 'RECORD::ADD_TO',

    ADD_CURRENT_LETTER: 'RECORD::ADD_CURRENT_LETTER',

    CLEAR_ERROR: 'RECORD:CLEAR_ERROR',

    CURRENT_LETTER: 'RECORD::CURRENT_LETTER',
    CURRENT_LETTER_FULFILLED: 'RECORD::CURRENT_LETTER_FULFILLED',
    CURRENT_LETTER_PENDING: 'RECORD::CURRENT_LETTER_PENDING',
    CURRENT_LETTER_REJECTED: 'RECORD::CURRENT_LETTER_REJECTED',
};
