/**
 * @constant
 * @desc every action type
 * @version 1.0
 * @since 1.0
 * @public
 */
export default {
    ME: 'ME::ME',
    CHANGE: 'ME::CHANGE',
    ME_PENDING: 'ME::ME_PENDING',
    ME_FULFILLED: 'ME::ME_FULFILLED',
    ME_REJECTED: 'ME::ME_REJECTED',
    UPDATE: 'ME::UPDATE',
    UPDATE_PENDING: 'ME::UPDATE_PENDING',
    UPDATE_FULFILLED: 'ME::UPDATE_FULFILLED',
    UPDATE_REJECTED: 'ME::UPDATE_REJECTED',
    LOGOUT: 'ME::LOGOUT',
    LOGOUT_PENDING: 'ME::LOGOUT_PENDING',
    LOGOUT_FULFILLED: 'ME::LOGOUT_FULFILLED',
    LOGOUT_REJECTED: 'ME::LOGOUT_REJECTED',
};
