/**
 * @constant
 * @desc every action type
 * @version 1.0
 * @since 1.0
 * @public
 */
export default {
    IDENTIFICATION: 'AUTH::IDENTIFICATION',
    IDENTIFICATION_PENDING: 'AUTH::IDENTIFICATION_PENDING',
    IDENTIFICATION_FULFILLED: 'AUTH::IDENTIFICATION_FULFILLED',
    IDENTIFICATION_REJECTED: 'AUTH::IDENTIFICATION_REJECTED',
    REFRESH: 'AUTH::REFRESH',
    REFRESH_PENDING: 'AUTH::REFRESH_PENDING',
    REFRESH_FULFILLED: 'AUTH::REFRESH_FULFILLED',
    REFRESH_REJECTED: 'AUTH::REFRESH_REJECTED',
    CLEAR_ERROR: 'AUTH:CLEAR_ERROR',
};
